//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavConfigHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WavConfigHelper.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bye!.
        /// </summary>
        internal static string STR_COMMAND_BYE {
            get {
                return ResourceManager.GetString("STR_COMMAND_BYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File &apos;{0}&apos; already exists!.
        /// </summary>
        internal static string STR_COMMAND_ERROR_FILE_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("STR_COMMAND_ERROR_FILE_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File &apos;{0}&apos; doesn&apos;t exist!.
        /// </summary>
        internal static string STR_COMMAND_ERROR_FILE_NOT_EXISTS {
            get {
                return ResourceManager.GetString("STR_COMMAND_ERROR_FILE_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reclist &apos;{0}&apos; already exists!.
        /// </summary>
        internal static string STR_COMMAND_ERROR_RECLIST_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("STR_COMMAND_ERROR_RECLIST_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reclist &apos;{0}&apos; doesn&apos;t exist!.
        /// </summary>
        internal static string STR_COMMAND_ERROR_RECLIST_NOT_EXISTS {
            get {
                return ResourceManager.GetString("STR_COMMAND_ERROR_RECLIST_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong arguments count!.
        /// </summary>
        internal static string STR_COMMAND_ERROR_WRONG_ARGS_COUNT {
            get {
                return ResourceManager.GetString("STR_COMMAND_ERROR_WRONG_ARGS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit helper.
        /// </summary>
        internal static string STR_COMMAND_EXIT_DESC {
            get {
                return ResourceManager.GetString("STR_COMMAND_EXIT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command failed..
        /// </summary>
        internal static string STR_COMMAND_FAILED {
            get {
                return ResourceManager.GetString("STR_COMMAND_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello! Welcome to WavConfigHelper. Type &apos;help&apos; to get commands list, or &apos;exit&apos; to exit..
        /// </summary>
        internal static string STR_COMMAND_HELLO {
            get {
                return ResourceManager.GetString("STR_COMMAND_HELLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get command list.
        /// </summary>
        internal static string STR_COMMAND_HELP_DESC {
            get {
                return ResourceManager.GetString("STR_COMMAND_HELP_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import 0.1 WavConfigTool project.
        /// </summary>
        internal static string STR_COMMAND_IMPORT_PROJECT_DESC {
            get {
                return ResourceManager.GetString("STR_COMMAND_IMPORT_PROJECT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на import_project %project file% %Reclist name in new version% %output filename%.
        /// </summary>
        internal static string STR_COMMAND_IMPORT_PROJECT_EXAMPLE1 {
            get {
                return ResourceManager.GetString("STR_COMMAND_IMPORT_PROJECT_EXAMPLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на import_project &quot;C:\voicebank.wconfig&quot; &quot;CVC RUS&quot; &quot;C:\voicebank.wsp&quot;.
        /// </summary>
        internal static string STR_COMMAND_IMPORT_PROJECT_EXAMPLE2 {
            get {
                return ResourceManager.GetString("STR_COMMAND_IMPORT_PROJECT_EXAMPLE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import .wsettings to .reclist.
        /// </summary>
        internal static string STR_COMMAND_IMPORT_RECLIST_DESC {
            get {
                return ResourceManager.GetString("STR_COMMAND_IMPORT_RECLIST_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на import_reclist %wsettings name% %output reclist name%.
        /// </summary>
        internal static string STR_COMMAND_IMPORT_RECLIST_EXAMPLE1 {
            get {
                return ResourceManager.GetString("STR_COMMAND_IMPORT_RECLIST_EXAMPLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на import_reclist &quot;C:\vccv_eng.wsettings&quot; &quot;VCCV English&quot;.
        /// </summary>
        internal static string STR_COMMAND_IMPORT_RECLIST_EXAMPLE2 {
            get {
                return ResourceManager.GetString("STR_COMMAND_IMPORT_RECLIST_EXAMPLE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command succeeded..
        /// </summary>
        internal static string STR_COMMAND_SUCCESS {
            get {
                return ResourceManager.GetString("STR_COMMAND_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Examples:.
        /// </summary>
        internal static string STR_EXAMPLE {
            get {
                return ResourceManager.GetString("STR_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown command &apos;{0}&apos;.
        /// </summary>
        internal static string STR_UNKNOWN_COMMAND {
            get {
                return ResourceManager.GetString("STR_UNKNOWN_COMMAND", resourceCulture);
            }
        }
    }
}
